version: '3'
services:
  flyway:
    image: redgate/flyway
    command: -url=jdbc:mysql://db:3306/example?autoreconnect=true&allowPublicKeyRetrieval=true -user=flyway -password=123456 validate
    volumes:
      - .:/flyway/sql
    depends_on:
      - db
    networks:
      - my_network
      
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3307:3306
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
