name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

jobs:
  SnykScan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Snyk Scan
      run: |
        pip install -r src/requirements.txt 
        npm install -g snyk
        snyk auth ยง{{secrets.SNYK_TOKEN}}
        snyk test
  
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  
      
    - name: Login to Docker Hub
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Build Docker image
      run: docker build -t ivnmaria/classwork-1:latest .

    - name: Push Docker image
      run: docker push ivnmaria/classwork-1
