name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:
  SonarCloudScan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master 
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         
  SnykScan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Snyk CLI
      run: npm install -g snyk@latest

    - name: Install dependecies
      run: pip install -r src/requirements.txt
      
    - name: Snyk Scan
      run: snyk test --all-projects
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  
  Build:
    runs-on: ubuntu-latest
    needs: ["SnykScan", "SonarCloudScan"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  
      
    - name: Login to Docker Hub
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Build Docker image
      run: docker build -t "python_app:1.0" .

    - name: Trivy Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ivnmaria/classwork-1:latest
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'HIGH'
          
    - name: Tag an image
      run: docker tag python_app:1.0 ivnmaria/classwork-1

    - name: Push Docker image
      run: docker push ivnmaria/classwork-1
