name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  SONAR_PROJECT_KEY: ivnmaria
  SONAR_ORGANIZATION: Maria I

jobs:
  SonarCloudScan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup SonarScanner
        run: |
          wdget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.zip
          unzip sonar-scanner-cli.zip
          export PATH="$PATH:$(pwd)/sonar-scanner-cli-5.0.1/bin"

      - name: Run SonarScanner
        run: sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.projectKey=your_project_key -Dsonar.organization=your_organization
        env:
          SONAR_TOKEN: ${f secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: ivnmaria
          SONAR_ORGANIZATION: Maria I
        
  SnykScan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Snyk CLI
      run: npm install -g snyk@latest

    - name: Install dependecies
      run: pip install -r src/requirements.txt
      
    - name: Snyk Scan
      run: snyk test --all-projects
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  
      
    - name: Login to Docker Hub
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Build Docker image
      run: docker build -t ivnmaria/classwork-1:latest .

    - name: Push Docker image
      run: docker push ivnmaria/classwork-1
