name: Unit tests, database migrations check and hardcoded secrets check

on:
  push:
    branches:
      - main

jobs:
  UnitTests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r src/requirements.txt

      - name: Run unit tests
        run: python3 -m unittest src/app_test.py

  DatabaseMigrations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull Docker image
        run: docker pull redgate/flyway

      - name: Database migrations check
        run: docker run --rm -v "$(pwd)/flyway/db:/flyway/db" -v "$(pwd)/flyway/migrations:/flyway/sql" -v "$(pwd)/flyway/config:/flyway/conf" redgate/flyway

  CheckSecrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install gitleaks
        run: gitleaks/setup-gitleaks@v7.6.0

      - name: Run gitleaks check
        run: gitleaks detect
