name: SonarCloud

on: 
  pull_request:
  
env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  SonarCloudScan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r src/requirements.txt 

      - name: Install coverage tool
        run: pip install coverage

      - name: Run tests and generate coverage
        run: |
          coverage run -m pytest
          coverage xml -i
        
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master 
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
